#! encoding=utf-8
from tysdk.entity.pay4.payment.payv4_168x import TuYouPay168XV4
from tysdk.entity.pay4.payment.payv4_16wifi import TuYouPay16WifiV4
from tysdk.entity.pay4.payment.payv4_360 import TuYouPay360V4
from tysdk.entity.pay4.payment.payv4_360pay import TuYouPay360payV4
from tysdk.entity.pay4.payment.payv4_aidongman import TuYouPayAiDongManV4
from tysdk.entity.pay4.payment.payv4_aigame import TuYouPayAiGameV4
from tysdk.entity.pay4.payment.payv4_aisi import TuYouPayAiSiV4
from tysdk.entity.pay4.payment.payv4_ali import TuYouPayAliV4
from tysdk.entity.pay4.payment.payv4_ali_app import TuYouPayAliAPPV4
from tysdk.entity.pay4.payment.payv4_ali_gateway import TuYouPayAliV4Gateway
from tysdk.entity.pay4.payment.payv4_alibig import TuYouPayAliBigV4
from tysdk.entity.pay4.payment.payv4_anzhi import TuYouPayAnZhiV4
from tysdk.entity.pay4.payment.payv4_base import PayBaseV4
from tysdk.entity.pay4.payment.payv4_bdgame import TuYouPayBDGameV4
from tysdk.entity.pay4.payment.payv4_changba import TuYouPayChangbaV4
from tysdk.entity.pay4.payment.payv4_coolpad import TuYouPayCoolpadV4
from tysdk.entity.pay4.payment.payv4_duoku import TuYouPayDuoKuV4
from tysdk.entity.pay4.payment.payv4_gefubigsdk import TuYouPayGeFuBigSdkV4
from tysdk.entity.pay4.payment.payv4_googleiab import TuyouPayGoogleIABV4
from tysdk.entity.pay4.payment.payv4_haimawan import TuYouPayHaiMaWanV4
from tysdk.entity.pay4.payment.payv4_huawei import TuYouPayHuaWeiV4
from tysdk.entity.pay4.payment.payv4_huiyuan import TuYouPayHuiYuanBaoYueV4
from tysdk.entity.pay4.payment.payv4_iTools import TuYouPayiToolsV4
from tysdk.entity.pay4.payment.payv4_iappay import TuYooIappayV4
from tysdk.entity.pay4.payment.payv4_iiapple import TuYouIIAppleV4
from tysdk.entity.pay4.payment.payv4_ios import TuYouPayIOSV4
from tysdk.entity.pay4.payment.payv4_jinli import TuYouPayJinliV4
from tysdk.entity.pay4.payment.payv4_jinlionline import TuYouPayJinliOnlineV4
from tysdk.entity.pay4.payment.payv4_jinritoutiao import TuYouPayJinritoutiaoV4
from tysdk.entity.pay4.payment.payv4_jiuxiu import TuYouPayJiuxiuV4
from tysdk.entity.pay4.payment.payv4_jolo import TuYouPayJoloV4
from tysdk.entity.pay4.payment.payv4_jusdk import TuYouPayJusdkV4
from tysdk.entity.pay4.payment.payv4_kuaiwan import TuYouPayKuaiwanV4
from tysdk.entity.pay4.payment.payv4_lenovo import TuYouPayLenovoV4
from tysdk.entity.pay4.payment.payv4_lenovodj import TuYouPayLenovoDanjiV4
from tysdk.entity.pay4.payment.payv4_letv import TuYouPayLetvV4
from tysdk.entity.pay4.payment.payv4_liantongwo import TuYouPayLianTongWoV4
from tysdk.entity.pay4.payment.payv4_liebao import TuYouPayLiebaoV4
from tysdk.entity.pay4.payment.payv4_lizi import TuYouPayLiziV4
from tysdk.entity.pay4.payment.payv4_ludashi import TuYouPayLudashiV4
from tysdk.entity.pay4.payment.payv4_m4399 import TuYouPayM4399V4
from tysdk.entity.pay4.payment.payv4_maopao import TuYouMaoPaoV4
from tysdk.entity.pay4.payment.payv4_meizu import TuYouPayMeizuV4
from tysdk.entity.pay4.payment.payv4_midashi import TuYouPayMiDaShiV4
from tysdk.entity.pay4.payment.payv4_momo import TuYouPayMomoV4
from tysdk.entity.pay4.payment.payv4_more import TuYouPayMoreV4
from tysdk.entity.pay4.payment.payv4_mumayi import TuYouPayMumayiV4
from tysdk.entity.pay4.payment.payv4_muzhiwan import TuYouPayMuzhiwanV4
from tysdk.entity.pay4.payment.payv4_now import TuYouNowV4
from tysdk.entity.pay4.payment.payv4_nubia import TuYouPayNubiaV4
from tysdk.entity.pay4.payment.payv4_oppo import TuyouPayOppoV4
from tysdk.entity.pay4.payment.payv4_papa import TuYouPayPapaV4
from tysdk.entity.pay4.payment.payv4_pengyouwan import TuYouPayPengyouwanV4
from tysdk.entity.pay4.payment.payv4_pps import TuYouPayPPSV4
from tysdk.entity.pay4.payment.payv4_ppzhushou import TuYouPayPPZhuShouV4
from tysdk.entity.pay4.payment.payv4_sougou import TuYouPaySougouV4
from tysdk.entity.pay4.payment.payv4_tongbutui import TuYouPayTongBuTuiV4
from tysdk.entity.pay4.payment.payv4_tuyoucard import PayTuyooCardV4
from tysdk.entity.pay4.payment.payv4_uc import TuYouPayUcV4
from tysdk.entity.pay4.payment.payv4_ucdj import TuYouPayUcDjV4
from tysdk.entity.pay4.payment.payv4_unionpay import PayUnionPayV4
from tysdk.entity.pay4.payment.payv4_vivo import TuYouPayVivoV4
from tysdk.entity.pay4.payment.payv4_vivounion import TuYouPayVivounionV4
from tysdk.entity.pay4.payment.payv4_wandoujia import TuYouPayWanDouJiaV4
from tysdk.entity.pay4.payment.payv4_wandoujiadanji import TuYouPayWandoujiadanji
from tysdk.entity.pay4.payment.payv4_weixin import PayWeixinV4
from tysdk.entity.pay4.payment.payv4_weixin_gateway import PayWeixinV4Gateway
from tysdk.entity.pay4.payment.payv4_wyxt import TuYouPayWYXTV4
from tysdk.entity.pay4.payment.payv4_xiaomi import TuYouPayXiaomiV4
from tysdk.entity.pay4.payment.payv4_xyzs import TuYouPayXYZSV4
from tysdk.entity.pay4.payment.payv4_ydjd import TuYouPayYdjdV4
from tysdk.entity.pay4.payment.payv4_ydmm import TuYouPayYdMmWeakV4
from tysdk.entity.pay4.payment.payv4_yee import TuYouPayYeeV4
from tysdk.entity.pay4.payment.payv4_yi import TuYouPayYiV4
from tysdk.entity.pay4.payment.payv4_yisdkpay import TuYouPayYiSdkV4
from tysdk.entity.pay4.payment.payv4_yiwan import TuYouPayYiwanV4
from tysdk.entity.pay4.payment.payv4_youku import TuYouPayYouKuV4
from tysdk.entity.pay4.payment.payv4_youkuh5 import TuYouPayYouKuH5V4
from tysdk.entity.pay4.payment.payv4_ysdk import TuYouPayYsdkV4
from tysdk.entity.pay4.payment.payv4_yygame import TuYouPayYYGameV4
from tysdk.entity.pay4.payment.payv4_zhangyue import TuYouPayZhangYueV4
from tysdk.entity.pay4.payment.payv4_zhuoyi import TuYouPayZhuoyiV4

