# -*- coding=utf-8 -*-

CHARGE_RATE_RMB = 1

# 支付的常量
PAY_STATE_IDEL = 0  # 初始的状态，开始进行交易
PAY_STATE_CHARGE = 1  # 充值开始
PAY_STATE_CHARGE_WAIT = 2  # 充值等待付款
PAY_STATE_CHARGE_OK = 3  # 充值,付款成功
PAY_STATE_CHARGE_ERROR = 4  # 充值,付款失败，签名验证失败
PAY_STATE_PAY_OK = 5  # 购买成功
PAY_STATE_PAY_ERROR = 6  # 购买失败
PAY_STATE_DELIVERY = 7  # 开始投递货物
PAY_STATE_DELIVERY_ERROR = 8  # 开始投递货物
PAY_STATE_DELIVERY_OK = 9  # 交易结束

PHONETYPE_CHINAMOBILE = "chinaMobile"
PHONETYPE_CHINAUNION = "chinaUnion"
PHONETYPE_CHINATELECOM = "chinaTelecom"
PHONETYPE_INTS = {PHONETYPE_CHINAMOBILE: 0, PHONETYPE_CHINAUNION: 1, PHONETYPE_CHINATELECOM: 2, 'other': 3}
