var local_msg_zh_cn = {
	'neterr' : '网络异常，请重试！',
	'syserr' : '系统错误！',
	'-9999' : '请您检查网络设置',
	'-2' : '客户端请求参数错误',
	'-1' : '客户端版本过低',
	'1' : '邮箱、密码不正确',
	'2' : '邮箱已经注册',
	'3' : '游客登录失败',
	'4' : '新用户注册失败',
	'5' : 'SNS用户注册失败',
	'6' : '旧密码错误',
	'register' : '注册',
	'loginByDevId' : '体验游戏',
	'loginByMail' : '登录',
	'but_ok' : '确&nbsp;定',
	'but_cancel' : '取&nbsp;消',
	'tip_mail1' : '请输入有效的邮箱',
	'tip_card_num' : '请输入有效的充值卡号',
	'tip_card_pwd' : '请输入有效的充值卡密码',
	'tip_pwd1' : '请输入有效的密码',
	'ty_coin' : '途游币',
	'buy_ok' : '购买成功！',
	'buy_error' : '购买失败！',
	'charge' : '充值',
	'pay_type' : '支付渠道：',
	'tuyou.ali' : '支付宝',
	'tuyou.caifutong' : '财付通',
	'xiaomi.common' : '小米支付',
	'360.ali' : '支付宝',
	'360.card.dx' : '电信充值卡',
	'360.card.lt' : '联通充值卡',
	'360.card.yd' : '移动充值卡',
	'tuyou.card.dx' : '电信充值卡',
	'tuyou.card.lt' : '联通充值卡',
	'tuyou.card.yd' : '移动充值卡',
	'charge_tip_1' : '请选择或输入充值卡得面值',
	'charge_tip_3' : '交易提交中，请勿重复点击',
	'charge_tip_4' : '交易付款中，请勿重复点击',
	'charge_tip_5' : '您的充值交易已经提交，请耐心等候...<br><br>您可以关闭此页面，继续游戏',
	'charge_tip_6' : '您的充值交易已经提交，请耐心等候...<br><br>请不要关闭此页面，以确保交易继续进行',
	'charge_tip_7' : '您的充值已经成功，请等候后续处理...<br><br>您可以关闭此页面，继续游戏',
	'charge_tip_8' : '<br><br><p style="color:#fff">您的充值操作失败，请重新进行充值</p>',
	'charge_error' : '<p style="color:#fff">交易失败，请重试<br>${0}',
	'buy_info_0' : '本次购买${0}物品共计花费${1}途游币<br>您的账户剩余${2}途游币',
	'buy_info_1' : '本次购买${0}物品共计花费${1}途游币<br>您的账户剩余${2}途游币<br><br><p style="color:#fff">在发送通知时出现错误，请联系客服处理',
	'buy_info_2' : '余额不足<br>${0}物品价格${1}途游币<br>您的账户余额为${2}途游币',
	'charge_tip_2' : '您充值的金额，不足以购买当前的商品<br>需要充值${0}途游币',
	'charge_tip' : '选择充值金额：（1元=${0}途币）',
	'rmb' : '元',
	'yee.card.JUNNET': '骏网一卡通', 
	'yee.card.SNDACARD': '盛大卡',
	'yee.card.SZX': '神州行',
	'yee.card.ZHENGTU': '征途卡', 
	'yee.card.QQCARD': 'Q币卡',
	'yee.card.UNICOM': '联通卡',
	'yee.card.JIUYOU': '久游卡',
	'yee.card.YPCARD': '易宝e卡通', 
	'yee.card.NETEASE': '网易卡',
	'yee.card.WANMEI': '完美卡',
	'yee.card.SOHU': '搜狐卡',
	'yee.card.TELECOM': '电信卡', 
	'yee.card.ZONGYOU': '纵游一卡通',
	'yee.card.TIANXIA': '天下一卡通',
	'yee.card.TIANHONG': '天宏一卡通'
};

var local_msg_current = local_msg_zh_cn;
