# -*- coding=utf-8 -*-
class Product(object):
    global_product = {
        'android_diamonds_1':
        {'10':
             [
              {'tyid':'D50', 'count' : 50, 'price': 5, 'name':'钻石x50', 'icon' : ''},
              {'tyid':'D100', 'count' : 100, 'price': 10, 'name':'钻石x100', 'icon' : ''},
              {'tyid':'D300', 'count' : 300, 'price': 30, 'name':'钻石x300', 'icon' : ''},
              {'tyid':'D500', 'count' : 500, 'price': 50, 'name':'钻石x500', 'icon' : ''},
              {'tyid':'D1000', 'count' : 1000, 'price': 100, 'name':'钻石x1000', 'icon' : ''},
              {'tyid':'D3000', 'count' : 3000, 'price': 300, 'name':'钻石x3000', 'icon' : ''},
              {'tyid':'D10000', 'count' : 10000, 'price': 1000, 'name':'钻石x10000', 'icon' : ''},
             ],
          '6':
            [
             {'tyid':'TY9999R0008001', 'count' : 80, 'price': 8, 'name':'钻石x80', 'icon' : ''},
             {'tyid':'TY9999R0050001', 'count' : 500, 'price': 50, 'name':'钻石x500', 'icon' : ''},
            ]
        },
        'ios_diamonds_1':
        {'10':
             [{'tyid':'DI60', 'price': 6, 'name':'钻石x60', 'iosid' : 'com.cn.douniu.tuyoo.product.d60'},
              {'tyid':'DI120', 'price': 12, 'name':'钻石x120', 'iosid' : 'com.cn.douniu.tuyoo.product.d120'},
              {'tyid':'DI180', 'price': 18, 'name':'钻石x180', 'iosid' : 'com.cn.douniu.tuyoo.product.d180'},
              {'tyid':'DI300', 'price': 30 , 'name':'钻石x300', 'iosid' : 'com.cn.douniu.tuyoo.product.d300'},
              {'tyid':'DI680', 'price': 68, 'name':'钻石x680', 'iosid' : 'com.cn.douniu.tuyoo.product.d680'},
              {'tyid':'DI1280', 'price': 128, 'name':'钻石x1280', 'iosid' : 'com.cn.douniu.tuyoo.product.d1280'},
              {'tyid':'DI3280', 'price': 328, 'name':'钻石x3280', 'iosid' : 'com.cn.douniu.tuyoo.product.d3280'},
              {'tyid':'DI6480', 'price': 648, 'name':'钻石x6480', 'iosid' : 'com.cn.douniu.tuyoo.product.d6480'},
             ],
         '6':
             [
              #{'tyid':'DI60',   'count' : 60,   'price': 6,   'name':'钻石x60',   'icon' : ''},
              #{'tyid':'DI120',  'count' : 120,  'price': 12,  'name':'钻石x120',  'icon' : ''},
              #{'tyid':'DI180',  'count' : 180,  'price': 18,  'name':'钻石x180',  'icon' : ''},
              #{'tyid':'DI300',  'count' : 300,  'price': 30,  'name':'钻石x300',  'icon' : ''},
              #{'tyid':'DI500',  'count' : 500,  'price': 50,  'name':'钻石x500',  'icon' : ''},
              #{'tyid':'DI680',  'count' : 680,  'price': 68,  'name':'钻石x680',  'icon' : ''},
              #{'tyid':'DI980',  'count' : 980,  'price': 98,  'name':'钻石x980',  'icon' : ''},
              #{'tyid':'DI1280', 'count' : 1280, 'price': 128, 'name':'钻石x1280', 'icon' : ''},
              #{'tyid':'DI1980', 'count' : 1980, 'price': 198, 'name':'钻石x1980', 'icon' : ''},
              #{'tyid':'DI3280', 'count' : 3280, 'price': 328, 'name':'钻石x3280', 'icon' : ''},
              #{'tyid':'DI6480', 'count' : 6480, 'price': 648, 'name':'钻石x6480', 'icon' : ''},
              {'tyid':'TY9999R0006001', 'count' : 60, 'price': 6, 'name':'钻石x60', 'icon' : ''},
              #{'tyid':'TY9999R0008001', 'count' : 80, 'price': 8, 'name':'钻石x80', 'icon' : ''},
              {'tyid':'TY9999R0030001', 'count' : 300, 'price': 30, 'name':'钻石x300', 'icon' : ''},
              #{'tyid':'TY9999R0050001', 'count' : 500, 'price': 50, 'name':'钻石x500', 'icon' : ''},
              #{'tyid':'TY9999R0098001', 'count' : 980, 'price': 98, 'name':'钻石x10000', 'icon' : ''},
              #{'tyid':'TY9999R0100001', 'count' : 1000, 'price': 100, 'name':'钻石x1000', 'icon' : ''},
              #{'tyid':'TY9999R0198001', 'count' : 1980, 'price': 198, 'name':'钻石x1980', 'icon' : ''},
              #{'tyid':'TY9999R0300001', 'count' : 3000, 'price': 300, 'name':'钻石x3000', 'icon' : ''},
              #{'tyid':'TY9999R0328001', 'count' : 3280, 'price': 328, 'name':'钻石x3280', 'icon' : ''},
              #{'tyid':'TY9999R0648001', 'count' : 6480, 'price': 648, 'name':'钻石x6480', 'icon' : ''},
              #{'tyid':'TY9999R1000001', 'count' : 10000, 'price': 1000, 'name':'钻石x10000', 'icon' : ''},
             ]
        },
        'android_products_1':
        {
        '8':
           [{'tyid':'TEXAS_IOS_COIN1', 'price': 6,   'name':'6万金币',   'iosid' : 'cn.com.dezhou.crazy.product.1'},
            {'tyid':'TEXAS_IOS_COIN2', 'price': 30,  'name':'33万金币',  'iosid' : 'cn.com.dezhou.crazy.product.2'},
            {'tyid':'TEXAS_IOS_COIN3', 'price': 98,  'name':'113万金币', 'iosid' : 'cn.com.dezhou.crazy.product.3'},
            {'tyid':'TEXAS_IOS_COIN4', 'price': 198, 'name':'228万金币', 'iosid' : 'cn.com.dezhou.crazy.product.4'},
            {'tyid':'TEXAS_IOS_COIN5', 'price': 328, 'name':'378万金币', 'iosid' : 'cn.com.dezhou.crazy.product.5'},
            {'tyid':'TEXAS_IOS_COIN6', 'price': 648, 'name':'778万金币', 'iosid' : 'cn.com.dezhou.crazy.product.6'},
            {'tyid':'TEXAS_IOS_VIP2',  'price': 98,  'name':'778万金币', 'iosid' : 'cn.com.dezhou.crazy.product.7'},
            {'tyid':'TEXAS_IOS_COIN_LUCKY_R6',  'price': 6,  'name':'10万金币', 'iosid' : 'TEXAS_IOS_COIN_LUCKY_R6'},
            #{'tyid':'TEXAS_IOS_ITEM_SEND_LED',  'price': 50,  'name':'喇叭', 'iosid' : 'TEXAS_IOS_ITEM_SEND_LED'},
            #{'tyid':'TEXAS_IOS_ITEM_RENAME_CARD',  'price': 98,  'name':'改名卡', 'iosid' : 'TEXAS_IOS_ITEM_RENAME_CARD'},
           ],
        '6':
            [
        #以下为商品信息
        {'tyid': 'TY9999D0006001', 'name':'60000金币', 'price':6,
         'charge_categories': [
             {'category': 'CAT_DUANDAI', 'desc': '', 'summary': '共6万',
              'tag':'', 'tagurl':'', 'extra_deliver': {},
              #'is_shortcut':'',
              },
             {'category':'CAT_ALIPAY', 'paytype': 'tuyou.ali',
              'desc': '加赠1.2万', 'summary': '共7.2万',
              'tag':'TAG_CHAOZHI', 'tagurl':'',
              'extra_deliver': {'chip':12000} },
             {'category': 'CAT_DEBIT_CARD', 'paytype': 'yee2.card1',
              'desc': '加赠1.2万', 'summary': '共7.2万',
              'tag':'', 'tagurl':'', 'extra_deliver': {} },
             {'category': 'CAT_CREDIT_CARD', 'paytype': 'yee2.card2',
              'desc': '加赠1.2万', 'summary': '共7.2万',
              'tag':'', 'tagurl':'', 'extra_deliver': {'chip':12000} },
             {'category':'CAT_PHONECHARGE_CARD',
              'paytype': ['tuyou.card.yd', 'tuyou.card.lt', 'tuyou.card.dx'],
              'desc': '加赠1.2万', 'summary': '共7.2万',
              'tag':'', 'tagurl':'',
              'extra_deliver': {'chip':12000} },
         ] },
        {'tyid': 'TY9999D0030001', 'name':'300000金币', 'price':30,
         'charge_categories': [
             {'category':'CAT_ALIPAY', 'paytype': 'tuyou.ali',
              'desc': '加赠6万', 'summary': '共36万',
              'tag':'TAG_CHAOZHI', 'tagurl':'',
              'extra_deliver': {'chip':60000} },
             {'category': 'CAT_DEBIT_CARD', 'paytype': 'yee2.card1',
              'desc': '加赠6万', 'summary': '共36万',
              'tag':'', 'tagurl':'', 'extra_deliver': {'chip':60000} },
             {'category': 'CAT_CREDIT_CARD', 'paytype': 'yee2.card2',
              'desc': '加赠6万', 'summary': '共36万',
              'tag':'', 'tagurl':'', 'extra_deliver': {'chip':60000} },
             {'category':'CAT_PHONECHARGE_CARD',
              'paytype': ['tuyou.card.yd', 'tuyou.card.lt', 'tuyou.card.dx'],
              'desc': '加赠6万', 'summary': '共36万',
              'tag':'', 'tagurl':'',
              'extra_deliver': {'chip':60000} },
         ] },
        {'tyid': 'TY9999D0050001', 'name':'500000金币', 'price':50,
         'charge_categories': [
             {'category':'CAT_ALIPAY', 'paytype': 'tuyou.ali',
              'desc': '加赠10万', 'summary': '共60万',
              'tag':'TAG_CHAOZHI', 'tagurl':'',
              'extra_deliver': {'chip':100000} },
             {'category': 'CAT_DEBIT_CARD', 'paytype': 'yee2.card1',
              'desc': '加赠10万', 'summary': '共60万',
              'tag':'', 'tagurl':'', 'extra_deliver': {} },
             {'category': 'CAT_CREDIT_CARD', 'paytype': 'yee2.card2',
              'desc': '加赠10万', 'summary': '共60万',
              'tag':'', 'tagurl':'', 'extra_deliver': {'chip':100000} },
             {'category':'CAT_PHONECHARGE_CARD',
              'paytype': ['tuyou.card.yd', 'tuyou.card.lt', 'tuyou.card.dx'],
              'desc': '加赠10万', 'summary': '共60万',
              'tag':'', 'tagurl':'',
              'extra_deliver': {'chip':100000} },
         ] },
        {'tyid': 'TY9999D0100001', 'name':'1000000金币', 'price':100,
         'charge_categories': [
             {'category':'CAT_ALIPAY', 'paytype': 'tuyou.ali',
              'desc': '加赠25万', 'summary': '共125万',
              'tag':'TAG_CHAOZHI', 'tagurl':'',
              'extra_deliver': {'chip':250000} },
             {'category': 'CAT_DEBIT_CARD', 'paytype': 'yee2.card1',
              'desc': '加赠25万', 'summary': '共125万',
              'tag':'', 'tagurl':'', 'extra_deliver': {'chip':250000} },
             {'category': 'CAT_CREDIT_CARD', 'paytype': 'yee2.card2',
              'desc': '加赠25万', 'summary': '共125万',
              'tag':'', 'tagurl':'', 'extra_deliver': {'chip':250000} },
             {'category':'CAT_PHONECHARGE_CARD',
              'paytype': ['tuyou.card.yd', 'tuyou.card.lt', 'tuyou.card.dx'],
              'desc': '加赠25万', 'summary': '共125万',
              'tag':'', 'tagurl':'',
              'extra_deliver': {'chip':250000} },
         ] },
        {'tyid': 'TY9999D0300001', 'name':'3000000金币', 'price':300,
         'charge_categories': [
             {'category':'CAT_ALIPAY', 'paytype': 'tuyou.ali',
              'desc': '加赠75万', 'summary': '共375万',
              'tag':'TAG_CHAOZHI', 'tagurl':'',
              'extra_deliver': {'chip':750000} },
             {'category': 'CAT_DEBIT_CARD', 'paytype': 'yee2.card1',
              'desc': '加赠75万', 'summary': '共375万',
              'tag':'', 'tagurl':'', 'extra_deliver': {'chip':750000} },
             {'category': 'CAT_CREDIT_CARD', 'paytype': 'yee2.card2',
              'desc': '加赠75万', 'summary': '共375万',
              'tag':'', 'tagurl':'', 'extra_deliver': {'chip':750000} },
             {'category':'CAT_PHONECHARGE_CARD',
              'paytype': ['tuyou.card.yd', 'tuyou.card.lt', 'tuyou.card.dx'],
              'desc': '加赠75万', 'summary': '共375万',
              'tag':'', 'tagurl':'',
              'extra_deliver': {'chip':750000} },
         ] },
        {'tyid': 'TY9999D1000001', 'name':'1000万金币', 'price':1000,
         'charge_categories': [
             {'category':'CAT_ALIPAY', 'paytype': 'tuyou.ali',
              'desc': '加赠300万', 'summary': '共1300万',
              'tag':'TAG_CHAOZHI', 'tagurl':'',
              'extra_deliver': {'chip':3000000} },
             {'category': 'CAT_DEBIT_CARD', 'paytype': 'yee2.card1',
              'desc': '加赠300万', 'summary': '共1300万',
              'tag':'', 'tagurl':'', 'extra_deliver': {'chip':3000000} },
             {'category': 'CAT_CREDIT_CARD', 'paytype': 'yee2.card2',
              'desc': '加赠300万', 'summary': '共1300万',
              'tag':'', 'tagurl':'', 'extra_deliver': {'chip':3000000} },
         ] },
        {'tyid': 'TY0006D0030002', 'name':'7天会员卡', 'price':30,
         'charge_categories': [
             {'category':'CAT_ALIPAY', 'paytype': 'tuyou.ali',
              'desc': '', 'summary': '共51万',
              'tag':'TAG_CHAOZHI', 'tagurl':'',
              'extra_deliver': {} },
             {'category': 'CAT_DEBIT_CARD', 'paytype': 'yee2.card1',
              'desc': '', 'summary': '共51万',
              'tag':'', 'tagurl':'', 'extra_deliver': {} },
             {'category': 'CAT_CREDIT_CARD', 'paytype': 'yee2.card2',
              'desc': '', 'summary': '共51万',
              'tag':'', 'tagurl':'', 'extra_deliver': {} },
             {'category':'CAT_PHONECHARGE_CARD',
              'paytype': ['tuyou.card.yd', 'tuyou.card.lt', 'tuyou.card.dx'],
              'desc': '', 'summary': '共51万',
              'tag':'', 'tagurl':'',
              'extra_deliver': {} },
         ] },
        {'tyid': 'TY0006D0100002', 'name':'30天会员卡', 'price':100,
         'charge_categories': [
             {'category':'CAT_ALIPAY', 'paytype': 'tuyou.ali',
              'desc': '', 'summary': '共190万',
              'tag':'TAG_CHAOZHI', 'tagurl':'',
              'extra_deliver': {} },
             {'category': 'CAT_DEBIT_CARD', 'paytype': 'yee2.card1',
              'desc': '', 'summary': '共190万',
              'tag':'', 'tagurl':'', 'extra_deliver': {} },
             {'category': 'CAT_CREDIT_CARD', 'paytype': 'yee2.card2',
              'desc': '', 'summary': '共190万',
              'tag':'', 'tagurl':'', 'extra_deliver': {} },
             {'category':'CAT_PHONECHARGE_CARD',
              'paytype': ['tuyou.card.yd', 'tuyou.card.lt', 'tuyou.card.dx'],
              'desc': '', 'summary': '共190万',
              'tag':'', 'tagurl':'',
              'extra_deliver': {} },
         ] },
        {'tyid': 'TY9999D0008001', 'name':'超值礼包', 'price':8,
         'charge_categories': [
             {'category': 'CAT_DUANDAI', 'desc': '', 'summary': '',
              'tag':'', 'tagurl':'', 'extra_deliver': {} },
             {'category':'CAT_ALIPAY', 'paytype': 'tuyou.ali',
              'desc': '加赠1.6万', 'summary': '',
              'tag':'TAG_CHAOZHI', 'tagurl':'',
              'extra_deliver': {'chip':16000} },
             {'category': 'CAT_DEBIT_CARD', 'paytype': 'yee2.card1',
              'desc': '加赠1.6万', 'summary': '',
              'tag':'', 'tagurl':'', 'extra_deliver': {'chip':16000} },
             {'category': 'CAT_CREDIT_CARD', 'paytype': 'yee2.card2',
              'desc': '加赠1.6万', 'summary': '',
              'tag':'', 'tagurl':'', 'extra_deliver': {'chip':16000} },
             {'category':'CAT_PHONECHARGE_CARD',
              'paytype': ['tuyou.card.yd', 'tuyou.card.lt', 'tuyou.card.dx'],
              'desc': '加赠1.6万', 'summary': '',
              'tag':'', 'tagurl':'',
              'extra_deliver': {'chip':16000} },
         ] },
        {'tyid': 'TY9999D0006002', 'name':'6元转运礼包', 'price':6,
         'charge_categories': [
             {'category': 'CAT_DUANDAI', 'desc': '', 'summary': '共11万',
              'tag':'', 'tagurl':'', 'extra_deliver': {} },
             {'category':'CAT_ALIPAY', 'paytype': 'tuyou.ali',
              'desc': '加赠1万', 'summary': '共12万',
              'tag':'TAG_CHAOZHI', 'tagurl':'',
              'extra_deliver': {'chip':10000} },
             {'category': 'CAT_DEBIT_CARD', 'paytype': 'yee2.card1',
              'desc': '加赠1万', 'summary': '共12万',
              'tag':'', 'tagurl':'', 'extra_deliver': {'chip':10000} },
             {'category': 'CAT_CREDIT_CARD', 'paytype': 'yee2.card2',
              'desc': '加赠1万', 'summary': '共12万',
              'tag':'', 'tagurl':'', 'extra_deliver': {'chip':10000} },
             {'category':'CAT_PHONECHARGE_CARD',
              'paytype': ['tuyou.card.yd', 'tuyou.card.lt', 'tuyou.card.dx'],
              'desc': '加赠1万', 'summary': '共12万',
              'tag':'', 'tagurl':'',
              'extra_deliver': {'chip':10000} },
         ] },
        {'tyid': 'TY9999D0008002', 'name':'8元转运礼包', 'price':8,
         'charge_categories': [
             {'category': 'CAT_DUANDAI', 'desc': '', 'summary': '共15万',
              'tag':'', 'tagurl':'', 'extra_deliver': {} },
             {'category':'CAT_ALIPAY', 'paytype': 'tuyou.ali',
              'desc': '加赠1万', 'summary': '共16万',
              'tag':'TAG_CHAOZHI', 'tagurl':'',
              'extra_deliver': {'chip':10000} },
             {'category': 'CAT_DEBIT_CARD', 'paytype': 'yee2.card1',
              'desc': '加赠1万', 'summary': '共16万',
              'tag':'', 'tagurl':'', 'extra_deliver': {'chip':10000} },
             {'category': 'CAT_CREDIT_CARD', 'paytype': 'yee2.card2',
              'desc': '加赠1万', 'summary': '共16万',
              'tag':'', 'tagurl':'', 'extra_deliver': {'chip':10000} },
             {'category':'CAT_PHONECHARGE_CARD',
              'paytype': ['tuyou.card.yd', 'tuyou.card.lt', 'tuyou.card.dx'],
              'desc': '加赠1万', 'summary': '共16万',
              'tag':'', 'tagurl':'',
              'extra_deliver': {'chip':10000} },
         ] },
    ]
        },
        'ios_products_1':
        {
         '6' : [
        {'tyid': 'TY9999D0006003', 'name':'6万金币', 'price':6,
         'iosid': 'cn.com.doudizhu.happy.1', },
        {'tyid': 'TY9999D0030003', 'name':'30万金币', 'price':30,
         'iosid': 'cn.com.doudizhu.happy.4', },
        {'tyid': 'TY9999D0098001', 'name':'98万金币（赠：30天记牌器）',
         'price':98, 'iosid': 'cn.com.doudizhu.happy.hall.1', },
        {'tyid': 'TY9999D0198001', 'name':'198万金币（赠：60天记牌器）',
         'price':198, 'iosid': 'cn.com.doudizhu.happy.hall.2', },
        {'tyid': 'TY9999D0328001', 'name':'328万金币（赠：100天记牌器）',
         'price':328, 'iosid': 'cn.com.doudizhu.happy.hall.3', },
        {'tyid': 'TY9999D0648001', 'name':'648万金币（赠：200天记牌器）',
         'price':648, 'iosid': 'cn.com.doudizhu.happy.hall.4', },
        {'tyid': 'TY0006D0030004', 'name':'7天会员卡（立得28万金币，每日登录可得3万金币（7天））',
         'price':30, 'iosid': 'cn.com.doudizhu.happy.hall.5', },
        {'tyid': 'TY0006D0098002', 'name':'30天会员卡（立得100万金币，每日登录可得3万金币（30天））',
         'price':98, 'iosid': 'cn.com.doudizhu.happy.hall.6', },
        {'tyid': 'TY9999D0006004', 'name':'超值礼包',
         'price':6, 'iosid': 'cn.com.doudizhu.happy.9', },
        {'tyid': 'TY9999D0006005', 'name':'6元转运礼包',
         'price':6, 'iosid': 'cn.com.doudizhu.happy.10', },
    ],
         '8':
           [{'tyid':'TEXAS_IOS_COIN1', 'price': 6,   'name':'6万金币',   'iosid' : 'cn.com.dezhou.crazy.product.1'},
            {'tyid':'TEXAS_IOS_COIN2', 'price': 30,  'name':'33万金币',  'iosid' : 'cn.com.dezhou.crazy.product.2'},
            {'tyid':'TEXAS_IOS_COIN3', 'price': 98,  'name':'113万金币', 'iosid' : 'cn.com.dezhou.crazy.product.3'},
            {'tyid':'TEXAS_IOS_COIN4', 'price': 198, 'name':'228万金币', 'iosid' : 'cn.com.dezhou.crazy.product.4'},
            {'tyid':'TEXAS_IOS_COIN5', 'price': 328, 'name':'378万金币', 'iosid' : 'cn.com.dezhou.crazy.product.5'},
            {'tyid':'TEXAS_IOS_COIN6', 'price': 648, 'name':'778万金币', 'iosid' : 'cn.com.dezhou.crazy.product.6'},
            {'tyid':'TEXAS_IOS_VIP2',  'price': 98,  'name':'778万金币', 'iosid' : 'cn.com.dezhou.crazy.product.7'},
            {'tyid':'TEXAS_IOS_COIN_LUCKY_R6',  'price': 6,  'name':'10万金币', 'iosid' : 'TEXAS_IOS_COIN_LUCKY_R6'},
            #{'tyid':'TEXAS_IOS_ITEM_SEND_LED',  'price': 50,  'name':'喇叭', 'iosid' : 'TEXAS_IOS_ITEM_SEND_LED'},
            #{'tyid':'TEXAS_IOS_ITEM_RENAME_CARD',  'price': 98,  'name':'改名卡', 'iosid' : 'TEXAS_IOS_ITEM_RENAME_CARD'},
           ],
          '10':
             [{'tyid':'COIN_6', 'price': 6, 'name':'钻石x60', 'iosid' : 'com.cn.douniu.tuyoo.product.d60'},
              {'tyid':'IOS_LOGIN_RAFFLE_6', 'price': 6, 'name':'钻石x60', 'iosid' : 'com.cn.douniu.tuyoo.product.d60'},
              {'tyid':'COIN_12', 'price': 12, 'name':'钻石x120', 'iosid' : 'com.cn.douniu.tuyoo.product.d120'},
              {'tyid':'COIN_18', 'price': 18, 'name':'钻石x180', 'iosid' : 'com.cn.douniu.tuyoo.product.d180'},
              {'tyid':'COIN_30', 'price': 30 , 'name':'钻石x300', 'iosid' : 'com.cn.douniu.tuyoo.product.d300'},
              {'tyid':'VIP_30', 'price': 30 , 'name':'钻石x300', 'iosid' : 'com.cn.douniu.tuyoo.product.d300'},
              {'tyid':'ZHUANYUN_30', 'price': 30 , 'name':'钻石x300', 'iosid' : 'com.cn.douniu.tuyoo.product.d300'},
              {'tyid':'COIN_68', 'price': 68, 'name':'钻石x680', 'iosid' : 'com.cn.douniu.tuyoo.product.d680'},
              {'tyid':'COIN_128', 'price': 128, 'name':'钻石x1280', 'iosid' : 'com.cn.douniu.tuyoo.product.d1280'},
              {'tyid':'COIN_328', 'price': 328, 'name':'钻石x3280', 'iosid' : 'com.cn.douniu.tuyoo.product.d3280'},
              {'tyid':'COIN_648', 'price': 648, 'name':'钻石x6480', 'iosid' : 'com.cn.douniu.tuyoo.product.d6480'},
             ],
        },
    }


    @classmethod
    def getProducts(cls, productkey):
        return cls.global_product[productkey]
